name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']


jobs:
  deploy:
    runs-on: debian
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/eggsbot
            git pull
            nohup python3 main.py